# Generated by Django 4.2.1 on 2023-06-10 06:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=64)),
                ("price", models.FloatField(blank=True, null=True)),
                ("purchase_stock", models.PositiveSmallIntegerField(default=1)),
                ("borrow_stock", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BookBorrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "allowed_borrow_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("return_datetime", models.DateTimeField(blank=True, null=True)),
                ("daily_cost", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("non-fiction", "Non-Fiction"),
                            ("sci-fi", "Science Fiction"),
                            ("fantasy", "Fantasy"),
                            ("mystery", "Mystery"),
                            ("romance", "Romance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "permitted_borrow_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("borrow_cost", models.FloatField(blank=True, null=True)),
                (
                    "income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_purchases",
                        related_query_name="book_purchase",
                        to="book.book",
                    ),
                ),
            ],
        ),
    ]
