# Generated by Django 4.2.1 on 2023-06-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="wallet",
                related_query_name="wallet",
                to="customer.customer",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                related_query_name="transaction",
                to="accounting.wallet",
            ),
        ),
    ]
